### ISSUE TITLE
can't change titleColor programmatically

### ISSUE THREAD

**Issue by azizimusa** [pavlospt/CircleView#15]
I have Language selection using circleview, click on 1 button, will apply my custom style. But only the titleColor i couldn't change.

**Comment by pavlospt** [comment]
Can you post your code snippet please?

**Comment by azizimusa** [comment]
CircleView cv = (CircleView) findViewById(R.id.circleview);
// below is what i can't do, it is not in the list.
cv.setTitleColor

**Comment by pavlospt** [comment]
Which version do you use?

**Comment by azizimusa** [comment]
1.0.0
