### ISSUE TITLE
Hexagon Equivalent

### ISSUE THREAD

**Issue by WanClem** [pavlospt/CircleView#16]
Hi,nice library...I know this is off topic but...Please would it be possible to create an hexagon equivalent around the text..I mean replacing the circle with an hexagon? If possible,can you help with procedure..  Once again,you just saved someone with this library...Thanks..I really appreciate...

**Comment by pavlospt** [comment]
Thank you for your kind words, but this is totally irrelevant to the purpose of the Library :) I can not provide such an ability.
