### ISSUE TITLE
Got ClassNotFoundException

### ISSUE THREAD

**Issue by lidox** [pavlospt/CircleView#19]
1. I use: compile 'com.github.pavlospt:circleview:1.3' 
2. I included:
`    <com.github.circleView
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="300dp"
        android:id="@+id/test"
        android:layout_height="300dp"
        app:cv_titleText="title"
        app:cv_subtitleText="subtitle"
        app:cv_titleSize="12dp"
        app:cv_subtitleSize="9dp"
        app:cv_fillRadius="0.9"
        app:cv_strokeWidthSize="5"/>`
3. Got Class not found:

 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.github.circleView" on path: DexPathList[[zip file "/data/app/....

Do you have any idea how to fix it using only gradle dependency?

**Comment by lidox** [comment]
Ok I fixed it: We should use following:

    **<com.github.pavlospt.CircleView**
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="300dp"
        android:id="@+id/test"
        android:layout_height="300dp"
        app:cv_titleText="title"
        app:cv_subtitleText="subtitle"
        app:cv_titleSize="12dp"
        app:cv_subtitleSize="9dp"
        app:cv_fillRadius="0.9"
        app:cv_strokeWidthSize="5"/>

Maybe you should note this on your readme! :)
I love your work! It looks amazing! :+1:

**Comment by pavlospt** [comment]
Thank you for your kind words. Will update the ReadMe as well.
