### ISSUE TITLE
Example App Link is Broken

### ISSUE THREAD

**Issue by roman-ku** [pavlospt/CircleView#20]
In the section `Apps using this library` the link to the `Hungry ` app is broken.

**Comment by pavlospt** [comment]
Works fine for me!

**Comment by roman-ku** [comment]
Oh, I see what the problem is. It's not available in the US.

![001105](https://cloud.githubusercontent.com/assets/10580420/22181112/52943762-e039-11e6-93d0-5e9fefd03d09.png)
