### ISSUE TITLE
How to apply a transparent fill color?

### ISSUE THREAD

**Issue by roman-ku** [pavlospt/CircleView#23]
Neither of these work (both result in a white fill color):

            // via code
            circleView.setFillColor(Color.TRANSPARENT);

            // via xml
            app:cv_fillColor="#00000000"

**Comment by Fabioluxx** [comment]
Simple Answer:
Use this together with setFillColor
`circleView.setBackgroundColor(Color.TRANSPARENT);`

That is because circleView default background color is white
Line 30 - CircleView.java:
`    private static int DEFAULT_BACKGROUND_COLOR = Color.WHITE;`
