### ISSUE TITLE
Fill Radius is offset 

### ISSUE THREAD

**Issue by charlesburks** [pavlospt/CircleView#24]
If I use ` app:cv_fillRadius="0.9"`, the inner circle seems to be a little offset to the top left. Using ` app:cv_fillRadius="0.95"` really offsets the ring and circle. Anyway to fix this?

Example for "0.9":
<img width="225" alt="screenshot 2018-05-09 10 19 05" src="https://user-images.githubusercontent.com/12037033/39826633-8e35e5ce-5372-11e8-84c6-6dbd378de968.png">

Example for "0.95":
<img width="224" alt="screenshot 2018-05-09 10 21 21" src="https://user-images.githubusercontent.com/12037033/39826720-ccd96f12-5372-11e8-9c34-c719c635a008.png">

**Comment by charlesburks** [comment]
Actually this may just be in Preview for the layout file. Seems to render as expected when compiled.

**Comment by pavlospt** [comment]
Thanks for trying it on runtime.  Not sure what would cause that to the XML preview :/
