### ISSUE TITLE
cv_titleSubtitleSpace may be not working?

### ISSUE THREAD

**Issue by azerphoenix** [pavlospt/CircleView#25]
Hello!
First of all than you so much for this library)
I tried to add space between title and subtitle and see this attribute. cv_titleSubtitleSpace="" Which types of params access this attribute? There is no information in docs... I tried to set it to 20 dp or sp and get errors.
Thanks in advance for yoor attention)

**Comment by pavlospt** [comment]
Hey @azerphoenix , thank you for your kind words! The value of that param is represented in float type!
