### ISSUE TITLE
makes the text optional

### ISSUE THREAD

**Issue by longkai** [pavlospt/CircleView#6]
Hi, another suggestion.

I want only show a circle without text, but the lib' s default behaviour is to set **Tile** and **Subtitle** and I have to set the text to "" in xml or programmatically which is annoying.

Please make the text optional, or if possible I can make a pull request:-)

**Comment by roman-ku** [comment]
This is not fixed. You still have to set the text to "" if you don't want it.

**Comment by pavlospt** [comment]
THis was never added. I mentioned above that it is not the intended behavior!

**Comment by roman-ku** [comment]
Hmm, when you said:

>In any case i am going to add a couple of checks and push the library.

I thought you meant that you will add checks to set the text to null if the title and/or subtitle attributes are not present in the XML.

**Comment by pavlospt** [comment]
For which case I added 2 booleans that handle the Title and Subtitle visibility :)

**Comment by roman-ku** [comment]
I see now. Didn't realize that was the implementation.
