### ISSUE TITLE
Attribute 'xxxxx' has already been defined

### ISSUE THREAD

**Issue by jwir3** [pavlospt/CircleView#9]
When using with another library (e.g. viewpagerindicator), android attribute definitions are global. This means that `fillColor`, for example, defined in both viewpagerindicator's attrs.xml and CircleView's attrs.xml conflict. (See also https://code.google.com/p/android/issues/detail?id=22576 ).

The solution to this is to prefix the attributes with something (for example, `PagerSlidingTabStrip` uses `psts`). Since `cv` is pretty common, I would suggest using pcv (shorthand for `pavlospt CircleView`). Thus, `fillColor` would become `pcvFillColor.

@pavlospt If you want, I can create a PR for you (Sorry I couldn't comment - apparently comments are limited)

**Comment by pavlospt** [comment]
Yes that's something that needs to be corrected. Will fix it when i find some time!

**Comment by pavlospt** [comment]
Fixed as of version 1.3. It is now being uploaded to MavenCentral and jCenter. Let me know if it works for you.
